apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: fv94mzlf1-go
  janus-idp.io/tekton: fv94mzlf1-go
  backstage.io/kubernetes-id: fv94mzlf1-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: fv94mzlf1-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
